### ISSUE TITLE
How to make moving event listener?

### ISSUE THREAD

**Issue by laka2012** [Unic8/controller-lib#1]
Hi, is there way to make moving event listener? So I want to continue moving event until finger leaves on screen. Is it possible from current version? Thank you.

**Comment by andretietz** [comment]
Hey, I just wanted to ask, if you found a solution for your problem. The events are by default captured until you leave your finger off the screen. Hope you found what you were searching for.

I am always interested in where people insert the library into, I would put it into the readme if you like. Would you be willing to tell me where you use it?

**Comment by laka2012** [comment]
Hi, thanks for reply! Yes, I find how to make it, all events are captured that animation thread, I should not manage myself. Your controller is awesome! easy using! I try to make a game at moment, just begin, will let you know what app is when I finish it. Thanks again.
